apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod1
spec:          
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  affinity:  
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      #pod labels
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod1
        topologyKey: topology.kubernetes.io/zone
        matchLabelKeys:
        - pod-template-hash        
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
