apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  affinity:  
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      #pod labels
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pod1
            - pod2
        topologyKey: topology.kubernetes.io/zone      
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
